Models/Entity/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanGroupProjeA.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Mail { get; set; }
        public string PhoneNumber { get; set; }
        public string Tc { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
    }
}

Models/Entity/ModelHg.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanGroupProjeA.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HgProjeAEntities : DbContext
    {
        public HgProjeAEntities()
            : base("name=HgProjeAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
    }
}

Models/Entity/ModelHg.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Hüseyin\source\repos\HumanGroupProjeA\Models\Entity\ModelHg.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Entity/ModelHg.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HumanGroupProjeA.Models.Entity;

namespace HumanGroupProjeA.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer

        HgProjeAEntities db = new HgProjeAEntities();
        public ActionResult Index()


        {
            var customers=db.Customer.ToList();
            return View(customers);
        }

        [HttpGet]
        public ActionResult AddCustomer()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult AddCustomer(Customer x)
        {
            db.Customer.Add(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CustomerDelete( int id) 
        {
            var customer=db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult CustomerEdit( int id)
        {
            var x=db.Customer.Find(id);
            return View("CustomerEdit",x);
        }

        public ActionResult CustomerUpdate(Customer x)
        {
            var Cst = db.Customer.Find(x.ID);
            Cst.Name = x.Name;
            Cst.Surname = x.Surname;
            Cst.PhoneNumber = x.PhoneNumber;
            Cst.Education= x.Education;
            Cst.Gender=x.Gender;
            Cst.Tc=x.Tc;
            Cst.Mail=x.Mail;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Customer/AddCustomer.cshtml
@model HumanGroupProjeA.Models.Entity.Customer
@{
    ViewBag.Title = "AddCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
div{
    margin-top:20px;
}
</style>

<h2>AddCustomer</h2>

<form class="form" method="post">

    <div>
        <label>
            Name
        </label>
        <input type="text" class="form-control" name="Name" placeholder="Name" />
    </div>
    <div>
        <label>
            Surname
        </label>
        <input type="text" class="form-control" name="Surname" placeholder="Surname" />
    </div>
    <div>
        <label>
            Mail
        </label>
        <input type="text" class="form-control" name="Mail" placeholder="Email" />
    </div>
    <div>
        <label>
            Phone Number
        </label>
        <input type="text" class="form-control" name="PhoneNumber" placeholder="Phone Number" maxlength="10" />
    </div>
    <div>
        <label style="font-style:italic">
            TC Number
        </label>
        <div><input type="text" class="form-control" name="Tc" placeholder="TC" maxlength="11" /></div>
    </div>
    <div>
        <label style="margin-bottom:10px">Gender</label>
        <br />
        <input type="radio" class="form-check-input" name="Gender" id="erkek" value="Erkek" />
        <label for="erkek">Erkek</label>
        <input type="radio" class="form-check-input" name="Gender" id="kadin" value="Kadın" />
        <label for="kadin">Kadın</label>
    </div>
    <div>
        <label for="edu"> Education </label>
        <select name="Education" id="education">
            <option value="Lisans">Lisans</option>
            <option value="Ön Lisans">Ön Lisans</option>
            <option value="Lise">Lise</option>
            <option value="Ortaokul">Ortaokul</option>
        </select>
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info" id="btn">Add</button>
    </div>
</form>

Views/Customer/CustomerEdit.cshtml
@model HumanGroupProjeA.Models.Entity.Customer
@{
    ViewBag.Title = "CustomerEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("CustomerUpdate", "Customer", FormMethod.Post))
{
    <div class="form">
        <div>
            <label>ID</label>
            @Html.TextBoxFor(x => x.ID, new { @class = "form-control" ,disabled="true" })
        </div>
        <div>
            <label>Name</label>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
        <div>
            <label>Surname</label>
            @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
        </div>
        <div>
            <label>Mail</label>
            @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
        </div>
        <div>
            <label>Phone Number</label>
            @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
        </div>
        <div>
            <label>Tc</label>
            @Html.TextBoxFor(x => x.Tc, new { @class = "form-control" })
        </div>
        <div>
            <label>Gender</label>
            @Html.TextBoxFor(x => x.Gender, new { @class = "form-control" })
        </div>
        <div>
            <label>Education</label>
            @Html.TextBoxFor(x => x.Education, new { @class = "form-control" })
        </div>
        <div>
            <button class="btn btn-primary">Update</button>
        </div>
    </div>
    

}

Views/Customer/Index.cshtml
@using HumanGroupProjeA.Models.Entity
@model List<Customer>
@{
    ViewBag.Title = "Customer Service";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customers</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Mail</th>
        <th>PhoneNumber</th>
        <th>TC</th>
        <th>Gender</th>
        <th>Education</th>
        <th>Delete</th>
        <th>Update</th>

    </tr>
    @foreach(var x in Model) { 
    <tr>
        <td>@x.ID</td>
        <td>@x.Name</td>
        <td>@x.Surname</td>
        <td>@x.Mail</td>
        <td>@x.PhoneNumber</td>
        <td>@x.Tc</td>
        <td>@x.Gender</td>
        <td>@x.Education</td>
        <td><a href="/Customer/CustomerDelete/@x.ID" class="btn btn-danger">Delete</a></td>
        <td><a href="/Customer/CustomerEdit/@x.ID" class="btn btn-success">Update</a></td>

    </tr>
    }
    
</table>
<a href="/Customer/AddCustomer" class="btn btn-secondary">Add New Customer</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Customer Service", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                   
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>